### ISSUE TITLE
Split message configuration into seperate file

### ISSUE THREAD

**Issue by MightyKnight** [arthurbambou/Fabric---Discord-Link#107]
#### Is your feature request related to a problem?
When I started documenting the current options of Fabric-Discord-Link, I noticed how many individual settings there are.
The current configuration file has an overwhelming amount of options that can make it quite hard to edit or document.  
This is especially demonstrated by **multiple message fields** existing, one of which (for `discordToMinecraft` is buried inbetween other settings.

### The suggestion
Create a new configuration file `messages.json` containing all custom message texts.

It would contain the following contents in combination with issue [#108](https://github.com/arthurbambou/Fabric---Discord-Link/issues/108) (removing `useCustomMessage`):

```yaml
{
  "minecraftToDiscord": {
     "playerMessage": "[%player] %message",
     "serverStarting": "Server is starting!",
     "serverStarted": "Server Started.",
     "serverStopping": "Server is stopping!",
     "serverStopped": "Server Stopped.",
     "playerJoined": "%player joined the game",
     "playerJoinedRenamed": "%new (formerly known as %old) joined the game",
     "playerLeft": "%player left the game",
     "advancementTask": "%player has made the advancement %advancement",
     "advancementChallenge": "%player has completed the challenge %advancement",
     "advancementGoal": "%player has reached the goal %advancement",
     "deathMsgPrefix": "",
     "deathMsgPostfix": ""
  },
  "discordToMinecraft": {
     "message": "[%player] %message"
  }
}
```

The directory structure would look like this, with a folder `fdlink` containing both files:
![grafik](https://user-images.githubusercontent.com/38622942/94931490-1b203d00-04c8-11eb-8da9-8af14f52c80a.png)

### Benefits
- Easily import/export existing message configuration
- Split documentation and make it more readable
- Differentiation between options and messages, clearer editing

### Considerations
- [x] Provide an upgrade routine from the old config, e.g. copying values over to the new file to prevent data loss
- [ ] Evaluate whether `emojiMap` also belongs into messages
